name: HTML Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  html-lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install HTMLHint
      run: npm install -g htmlhint
    
    - name: Lint HTML files
      run: htmlhint "*.html"
    
    - name: Check HTML validity
      run: |
        for file in *.html; do
          echo "Checking $file"
          curl -s -H "Content-Type: text/html; charset=utf-8" \
            --data-binary @"$file" \
            https://validator.w3.org/nu/?out=json | \
            jq '.messages[] | select(.type == "error")' || true
        done
